[package]
name = "ike-toml"
version = "0.1.0"
edition = "2021"

[dependencies]
ike-logger = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
ike-fs = { workspace = true }
thiserror = { workspace = true }